### PR TITLE
Syntax errors on try catch

### PR DESCRIPTION
**Pull request by BesnikMahmuti-Prosperoware**
**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [ ] Tests
- [ ] Typescript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Comment by eps1lon** [comment]
Could you explain what you're trying to do? Seems like old commits that are already released.

**Comment by BesnikMahmuti-Prosperoware** [comment]
I'm getting syntax error's when I import this "import '@testing-library/jest-dom/extend-expect'" on my code, when I fixed these syntax errors it worked fine.

**Comment by eps1lon** [comment]
> I'm getting syntax error's when I import this "import '@testing-library/jest-dom/extend-expect'" on my code,

This repository contains no code related to `@testing-library/jest-dom`. Can you share code reproducing the problem first so that we can identify what the issue is?

It's not apparent what specifically you fixed since it seems like you based your work on an older branch. Be sure to branch off of the latest version of `master`.

**Comment by kentcdodds** [comment]
I'll close this PR. Go ahead and make another PR if you feel it's needed. Thanks!

**Pull request closed without merging**
