### PR TITLE
Limit use of realTimers to Jest's fakeTimers

### PR DESCRIPTION
**Pull request by kgregory**
**What**:

Modify `runWithRealTimers` so that real timers are only used if they were faked by Jest's legacy or modern implementation of fake timers.

Also, when restoring Jest's fakes, be explicit in specifying whether we're restoring the `modern` or `legacy` fakes.

**Why**:

A recent change to `runWithRealTimers` added a check for the `clock` attribute on `setTimeout` so that we can determine whether timers were faked with Jest's modern fake timers (which are based on `@sinonjs/fake-timers`).  See [issue thread](https://github.com/testing-library/dom-testing-library/issues/612#issuecomment-645491120).

Unfortunately, this attribute can be present when users are not using Jest's fake timers and are using sinonjs.  Also, when `useFakeTimers` are invoked without parameters in Jest 26, the legacy timers are used by default.

**How**:

Determine if Jest legacy timers are used by checking `globalObj.setTimeout._isMockFunction`.

Determine if Jest modern timers are used by checking for the presence of `globalObj.setTimeout.clock` and also by verifying that use of `jest.getRealSystemTime` is supported.  It was introduced in Jest 26 and is only available when modern fake timers are used.

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [X] Tests
- [ ] Typescript definitions updated
- [X] Ready to be merged

### CODE REVIEW

**Comment by kgregory** [comment]
Thanks @kentcdodds, feels good to have contributed.

**Comment by kentcdodds** [comment]
@all-contributors please add @kgregory for code and tests

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Pull request merged**
