### PR TITLE
release: 10.0.0

### PR DESCRIPTION
**Pull request by eps1lon**
### Bug Fixes

* use defineProperty on the error object instead of setting the message directly ([#1268](https://github.com/testing-library/dom-testing-library/issues/1268)) ([3580f25](https://github.com/testing-library/dom-testing-library/commit/3580f25bd765cedb70889b2cf716085023d8c314)), closes [#1259](https://github.com/testing-library/dom-testing-library/issues/1259)

### Features

* upgrade aria-query to 5.3.0 ([#1241](https://github.com/testing-library/dom-testing-library/issues/1241)) ([2c57055](https://github.com/testing-library/dom-testing-library/commit/2c570553d8f31b008451398152a9bd30bce362b3)), closes [#1240](https://github.com/testing-library/dom-testing-library/issues/1240)

### BREAKING CHANGES

* new version of `aria-query` changes various roles. Check out the changed tests in [2c57055](https://github.com/testing-library/dom-testing-library/commit/2c570553d8f31b008451398152a9bd30bce362b3) to get an overview about what changed.

### Bug Fixes

* **role-helpers:** refine logRoles fn types ([#1249](https://github.com/testing-library/dom-testing-library/issues/1249)) ([5e03343](https://github.com/testing-library/dom-testing-library/commit/5e0334390f691366f8bab4123a4d1acd44665dc0))

### Features

* Add support for Node 20.x ([#1255](https://github.com/testing-library/dom-testing-library/issues/1255)) ([452097b](https://github.com/testing-library/dom-testing-library/commit/452097b35a207341f5328b997dfc901461a4e9d9))

### BREAKING CHANGES

* Minimum supported Node.js version is now 18.x

* update node version in codesandbox

* drop support for node 16 too

### CODE REVIEW

**Comment by jlp-craigmorten** [comment]
Is it worth adding to the release notes that #1241 also closes #1100, #1150, #1201, #1234, #1239?

**Comment by kasperpeulen** [comment]
Any plans for when to release this? @eps1lon

**Comment by eps1lon** [comment]
@MatanBobi Started the release train but then real life happened so I don't think anybody is actively driving this.

**Comment by MatanBobi** [comment]
Yeah, I indeed didn't get a chance to follow through on this release because I didn't have enough spare time.
We still want to test this release in some projects before releasing to see we're not missing anything regarding behavior changes.

**Comment by MatanBobi** [comment]
I've ran some tests on project I work on and they pass with no regression.
I'll mark this as ready for review and will try to push it soon.

**Review by timdeschryver — APPROVED** [review]
LGTM.
Fyi, This version didn't break a test in our case.

**Comment by eps1lon** [comment]
RTL is green with DTL 10: https://github.com/testing-library/react-testing-library/pull/1293

**Pull request merged**
