### PR TITLE
fix(within): Add extra type paramater to allow reassigning in TypeScript

### PR DESCRIPTION
**Pull request by Dennis273**
**What**:

Closes https://github.com/testing-library/react-testing-library/issues/979

TS error occurs when reassigning the return value of `within`

```typescript
import { screen, within } from "@testing-library/dom";
import "@types/jest";
import "@testing-library/jest-dom";

const navigation = screen.getByRole("navigation");
let breadcrumbs = within(navigation);
expect(breadcrumbs.getByRole("link", { name: /home/i })).toBeInTheDocument();
// ts error occurs
breadcrumbs = within(navigation);
```

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZwMZQKYYHYBo4DuwMAFsNnAL5wBmUEIcARAAIwbIzkDmAtADbAARlACGUAJ4B6ACYMmAbgBQoSLGZsJYDlIBWHGIpXho8Vu048BwsZL0HeckEaWoI2TnGyiAbsG6iXO5wALwo6FjYAHTcGDAAQhIAShD8GAAUTN5+AUHYTACUymnwIhiiMugAriBCyKGExGTY6dn+gcDuRUoYAB7aqDDpZRXVtcgxcYkpaZmC2ADWTPhI3iAYAFxwUiQMGFLAVAUFUTAQ8RgAktgAKiQYACIQqDU4Q90jlVA1dQ1EpORWr52nkikA

**Why**:

To avoid TS error or type-casting.

**How**:

The type error happens because TS tries to infer `T` from  the variable `breadcrumbs`(`BoundFunctions<T>`) in the demo above. This is fixed by adding another generic variable `K`.

**Checklist**:

- [N/A ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [x] Tests
- [x] TypeScript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Review by timdeschryver — APPROVED** [review]
LGTM

**Review by eps1lon — APPROVED** [review]
No idea why this works. Added some more tests/comments to make sure this isn't reverted before checking git-blame.

**Comment by eps1lon** [comment]
@all-contributors add @robcaldecott for bug
@all-contributors add @Dennis273 for code

**Comment by eps1lon** [comment]
@all-contributors add @robcaldecott for bug

**Comment by eps1lon** [comment]
@all-contributors add @Dennis273 for code

**Comment by eps1lon** [comment]
@all-contributors add @Dennis273 for code

**Pull request merged**
