### PR TITLE
feat: Enhance `ByText` error with `selector`

### LINKED ISSUE #1158: Display provided `selector` in *ByText error message
### Describe the feature you'd like:

When `getByText` returns an error message it currently does not mention if any selector other than "*" was provided to the query and returns the prettied body. (Where you might actually see the text you are looking for...)

Adding any selector different than "*" might bring attention to them to the reviewer of the test straight from the error message and help understand why it wasnt found.

### Suggested implementation:

In `src/queries/text.ts`:
```typescript
const getMissingError: GetErrorFunction<[Matcher, SelectorMatcherOptions]> = (
  c,
  text,
  options = {},
) => {
  const {collapseWhitespace, trim, normalizer, selector} = options
  const matchNormalizer = makeNormalizer({collapseWhitespace, trim, normalizer})
  const normalizedText = matchNormalizer(text.toString())
  const isNormalizedDifferent = normalizedText !== text.toString()
  const isUsingSelector = selector !== "*";
  return `Unable to find an element with the text: ${
    isNormalizedDifferent
      ? `${normalizedText} (normalized from '${text}')`
      : text
  }${
    isUsingSelector
      ? `, which satisfies selector: '${selector}'
      : ""
  }. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.`
}

```

### Describe alternatives you've considered:

I did not see much alternatives to draw attention to the selector other than this suggestion.

### Teachability, Documentation, Adoption, Migration Strategy:

As this is only adding information to the error messages if a praticular feature is used, I doubt the documentation would require any change, adoption or migration, unless the messages are parsed in some way...

### PR DESCRIPTION
**Pull request by raplemie**
**What**: fixes #1158 

**Why**:  The selector option behavior might not be well known by everyone reading the tests, and current test error output does not mention that additional requirement of the element being searched (which might be shown in the prettyDOM, similar reasonning to #450)

**How**: By adding a conditional to the error message genereated which have access to the used selector, and display it in the case it is not `undefined` (function called directly) and different from `"*"` (default selector for `getByText`)

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs) N/A
- [x] Tests
- [ ] TypeScript definitions updated N/A
- [x] Ready to be merged

### CODE REVIEW

**Review by timdeschryver — APPROVED** [review]
Looks good to me 👍

**Review by eps1lon — CHANGES_REQUESTED** [review]
Thanks. You've checked that docs were added but I don't see a PR to the docs page (https://github.com/testing-library/testing-library-docs/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Araplemie)?

**Comment by raplemie** [comment]
> Thanks. You've checked that docs were added but I don't see a PR to the docs page (https://github.com/testing-library/testing-library-docs/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Araplemie)?

I checked the docs checkmark because it was "handled" as N/A, not added. The error messages are not documented in the docs, so it didnt seem to require a docs change, but since the PR been sleeping for a months I thought that maybe this was automated that it had to be checked for it to process any further.

**Review by eps1lon — APPROVED** [review]
Oh, I only glanced at this, saw documentation checked and thought it needed docs but docs were forgotten. 

But this doesn't add `selector` to `ByText`. It just adds it to the error message. Thank you for clarifying 👍🏻

**Comment by eps1lon** [comment]
@all-contributors add @raplemie for code

**Comment by raplemie** [comment]
Thanks for merging!

**Pull request merged**
