### PR TITLE
feat: enhance byText missing error

### PR DESCRIPTION
**Pull request by MatanBobi**
Resolves https://github.com/testing-library/dom-testing-library/issues/450.

Basically all I did was run the same normalize function that runs later on as part of the errors flow too.
This is a naive solution, I'm more than happy to see if I missed something there :)

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
that's not a chore though. it's changing behavior the user can see. feature seems appropriate?

**Review by timdeschryver — APPROVED** [review]
+1 for merging this as a `feat`

**Comment by MatanBobi** [comment]
@eps1lon @timdeschryver
Definitely, good point. It was my bad :)
Thanks!

**Comment by MatanBobi** [comment]
@all-contributors please add @eps1lon and @timdeschryver for review :)

**Comment by MatanBobi** [comment]
@all-contributors please add @timdeschryver for review :)

**Pull request merged**
