### PR TITLE
performance improvement

### PR DESCRIPTION
**Pull request by rluvaton**
**What**: just performance improvment

**Why**: spreading the big array can be costly

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [ ] Tests
- [ ] TypeScript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
How did you measure? What are the before and after values?

**Comment by rluvaton** [comment]
I did not measure this specifically, but measured the merge array options:

<details>
<summary>The code</summary>

```javascript
const b = require('benny')
const { faker } = require('@faker-js/faker');

function generateArr() {
  return Array.from({
    length: faker.datatype.number({
      min: 25,
      max: 200,
    }),
  }, () => ({}));
}


const size = 50;
const allOptions = Array.from(
  { length: size },
  () => {
    const arr = [generateArr(), faker.datatype.boolean() ? [] : [faker.datatype.number()]];

    arr.push(faker.helpers.arrayElements(arr[0], faker.datatype.number({ min: 1, max: 10 })));
    return arr;
  },
);
let index = 0;

b.suite(
  'Merge Arrays',

  b.add('current - spread both', function () {
    const [big, small] = allOptions[index % size];

    const data = [...small, ...big];

    index++;
  }),

  b.add('concat', function () {
    const [big, small] = allOptions[index % size];

    const data = small.concat(big)

    index++;
  }),

  b.add('concat smaller array', function () {
    const [, small, bigAfterFilter] = allOptions[index % size];

    const data = small.concat(bigAfterFilter);

    index++;
  }),

  b.cycle(),
  b.complete(),
)
```

</details>

The results:
```js
  current - spread both:
    2 505 686 ops/s, ±0.56%    | slowest, 77.29% slower

  concat:
    8 202 593 ops/s, ±0.20%    | 25.67% slower

  concat smaller array:
    11 034 817 ops/s, ±0.09%   | fastest

Finished 3 cases!
  Fastest: concat smaller array
  Slowest: current - spread both

```

The `concat smaller array` is suppose to be the elements array after filtering

**Comment by eps1lon** [comment]
Benchmarks of the library are relevant here not synthetic benchmarks of similar code.

**Comment by rluvaton** [comment]
The reason why I did not make a library benchmark is that I wanted to avoid any possible caching so I'll have more realistic results and test different queries...

I'll try to create one now...

**Comment by rluvaton** [comment]
After running the application benchmark I did not saw any difference which is weird but closing anyway 🤷🏻‍♂️

**Pull request closed without merging**
