### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by rajagopalpalani**
To support latest react version

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [ ] Tests
- [ ] TypeScript definitions updated
- [ ] Ready to be merged

### CODE REVIEW

**Comment by MatanBobi** [comment]
@rajagopalpalani Can you please provide more context into why this change is needed?

**Comment by lukeapage** [comment]
I just coincidentally came across this because typescript performance analyse pointed this out as a duplicate package in node_modules. Its to upgrade so they can be deduped.

**Comment by MatanBobi** [comment]
What's the reason it's duplicated? Is that only for your package? I don't see a reason for this to be duplicated in our repo.

**Comment by lukeapage** [comment]
We depend on testing library and jest and jest is upgraded and testing library is not.

I have no idea if this pr is correct or not but why wouldn’t you want to regularly update to the latest version ?

**Comment by MatanBobi** [comment]
Since we're following semver, we need to understand if this should cause a major upgrade in our library which we just made. I'm not sure and I currently don't have the time to invest in understanding what are the changes in `pretty-format`. If we're exporting some of it's functionalities, this might break our API.

**Comment by rajagopalpalani** [comment]
I thought version was an issue. I am closing this MR. Its an issue from our end

**Pull request closed without merging**
