### PR TITLE
feat: Add support for firing all transition events

### PR DESCRIPTION
**Pull request by bpinto**
**What**:

Add support for firing [all transition events](https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent).

**Why**:

Currently only `transitionEnd` even is supported.

**How**:

Defining all other events, `transitionCancel`, `transitionRun`, `transitionStart`.

**Checklist**:

- [ ] Documentation added to the [docs site](https://github.com/testing-library/testing-library-docs)
- [x] Tests
- [x] TypeScript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
The PR is missing the changes from running `npm run format`.

Make sure that `npm run validate` passes locally.

**Comment by bpinto** [comment]
Sorry for the bad start, I knew I shouldn't have opened the PR yesterday as it was too late for me. I have properly formatted the code now.

`npm run validate` is failing locally (2 tests are failing) but same tests are failing on `main` branch. So I'm guessing it's something on my local environment that's not correctly setup.

**Comment by eps1lon** [comment]
> Sorry for the bad start, I knew I shouldn't have opened the PR yesterday as it was too late for me. I have properly formatted the code now.

There's nothing to appologize for. I just left the review so that you're notified of the CI failure since GitHub blocks CI for 1st time contributors.

> `npm run validate` is failing locally (2 tests are failing) but same tests are failing on `main` branch. So I'm guessing it's something on my local environment that's not correctly setup.

Yeah, we're not sure why these are failing for some people (myself included) locally but pass CI.

**Review by eps1lon — APPROVED** [review]

**Comment by bpinto** [comment]
@eps1lon about these two tests that are failing locally, if we remove the highlighting then they pass, not sure if you have noticed this.

```javascript
  const codeFrame = codeFrameColumns(
    rawFileContents,
    {
      start: {line, column},
    },
    {
      highlightCode: false, // no highlight
      linesBelow: 0,
    },
  )
  return `${frameLocation}\n${codeFrame}\n` // no dim
}

```

**Comment by eps1lon** [comment]
Thanks for looking into it! Could you open an issue so that we can track it better? Closed PRs are usually not watched

**Pull request merged**
