### PR TITLE
fix(types): add fourth param to build findAllBy and findBy queries

### LINKED ISSUE #534: findBy* & findAllBy* have wrong argument types for TS
- `DOM Testing Library` version: 7.2.0
- `node` version: 12.13.0
- `yarn` version: 1.22

### Relevant code or config:

```js
export const queryAllByAttribute = (
    container: HTMLElement,
    attribute: string,
    value: Matcher,
    options?: MatcherOptions
) => queryHelpers.queryAllByAttribute(attribute, container, value, options);

const includesAutomationId = (content: string, automationId: string) =>
    content.split(/\s+/).some(id => id === automationId);

export const queryAllByAutomationId = (
    container: HTMLElement,
    automationId: string | string[],
    options?: MatcherOptions
) =>
    queryAllByAttribute(
        container,
        TEST_ID_ATTRIBUTE,
        content => Array.isArray(automationId) ?
            automationId.every(id => includesAutomationId(content, id)) :
            includesAutomationId(content, automationId)
        ,
        options
    );

export const [
    queryByAutomationId,
    getAllByAutomationId,
    getByAutomationId,
    findAllByAutomationId,
    findByAutomationId
] = buildQueries(queryAllByAutomationId, getMultipleError, getMissingError);

const waitForOptions = { timeout: 2000 }

findByAutomationId(root, testId, options, waitForOptions), // <-  Expected 2-3 arguments, but got 4.ts(2554)
findAllByAutomationId(root, testId, options, waitForOptions), // <-  Expected 2-3 arguments, but got 4.ts(2554)
```

### What you did:

I generated custom `findBy` and `findAllBy` queries by `buildQueries`.

### What happened:

Generated queries have lost TypeScript types for 4th argument `waitForOptions`.

### Problem description:

I've noticed all `findBy*`/`findAllBy*` methods have 4th param, for example:

```ts
export type FindAllByText = (
    container: HTMLElement,
    id: Matcher,
    options?: SelectorMatcherOptions,
    waitForElementOptions?: WaitForElementOptions,
) => Promise<HTMLElement[]>;
```

However, `buildQueries` returns `FindBy` and `FindAllBy` queries without that param:

```ts
export type QueryMethod<Arguments extends any[], Return> = (container: HTMLElement, ...args: Arguments) => Return;

export type FindAllBy<Arguments extends any[]> = QueryMethod<Arguments, Promise<HTMLElement[]>>;
export type FindBy<Arguments extends any[]> = QueryMethod<Arguments, Promise<HTMLElement>>;
```

### Suggested solution:

Add 4th param type to the `QueryMethod` type or make special `FindQueryMethod` type with that param.

### PR DESCRIPTION
**Pull request by mzdunek93**
Fixes #534

### CODE REVIEW

**Comment by mzdunek93** [comment]
@eps1lon Sure.

**Comment by eps1lon** [comment]
@mzdunek93 Awesome! Very nice test.

**Comment by eps1lon** [comment]
@all-contributors add @mzdunek93  for code

**Comment by denysdovhan** [comment]
This PR makes those arguments required. They should be optional. @kentcdodds should I open another issue?

**Comment by kentcdodds** [comment]
Sure. Or you could open a PR of it's simple

**Comment by zorfling** [comment]
@denysdovhan - did this one ever get fixed? It looks like it's still an issue in master?
https://github.com/testing-library/dom-testing-library/blob/master/types/query-helpers.d.ts#L42

**Comment by denysdovhan** [comment]
@zorfling it's still relevant. Now the fourth argument of findAllBy and findBy is required. It should be optional.

**Comment by zorfling** [comment]
@denysdovhan I've added #794, so hopefully we'll get this one fixed soon.

**Pull request merged**
