### PR TITLE
test: fix coverage

### PR DESCRIPTION
**Pull request by kentcdodds**
**What**: fix coverage

**Why**: I merged https://github.com/testing-library/dom-testing-library/pull/381 without realizing that it didn't have 100% coverage. Now it wont be released. Unless I'm mistaken, we don't need to have coverage on that else branch because it's temporary code anyway.

**How**: add istabul ignore comment

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/alexkrolick/testing-library-docs) N/A
- [ ] I've prepared a PR for types targetting https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom N/A
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by kentcdodds** [comment]
cc @eps1lon, if this is incorrect and you can think of a test case we could write to get coverage on this, then feel free to add that. Thanks!

**Comment by eps1lon** [comment]
> cc @eps1lon, if this is incorrect and you can think of a test case we could write to get coverage on this, then feel free to add that. Thanks!

That particular bug is going to be fixed soon (PR has been approved and is waiting for merge+release). I'd rather remove this code altogether once it's fixed in jsdom.

**Comment by eps1lon** [comment]
Actually it's blocked by jest. https://github.com/facebook/jest/pull/8851 needs to be released (scheduled for v25) in order to get `jsdom@^15.2.0`.

**Pull request merged**
