### PR TITLE
fix(screen): broken link when there's no document

### PR DESCRIPTION
**Pull request by MatanBobi**
**What**: Fix a broken link when there's no document defined 

**Why**: The link is broken

**How**: I've put a link to the screen api definition. I couldn't find the page that was there before in the docs repo neither in the commits history.

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs) - N/A
- [X] Tests
- [ ] Typescript definitions updated - N/A
- [X] Ready to be merged

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
I think we just want to update the redirect in testing-library-docs. Links in error messages should always work since some users might not be able to upgrade the library.

**Comment by MatanBobi** [comment]
> I think we just want to update the redirect in testing-library-docs. Links in error messages should always work since some users might not be able to upgrade the library.

That's a good point. I'll close this one and add it to the docs. Thanks!

**Comment by eps1lon** [comment]
We don't need this anymore, right? The link is now valid.

**Comment by MatanBobi** [comment]
> We don't need this anymore, right? The link is now valid.

The link is valid but as I wrote above, I think that this fix should be in both places.. IMO we shouldn't rely on a redirect to always exist and should fix this here also.. WDYT?

**Comment by eps1lon** [comment]
We're actually less backwards compatible. Note that we can't change these links once published. If we decide to move the page then any version published will have 404 links. We could then decide to make redirect but we might as well use a permalink to begin with. Otherwise we have to maintain redirects for every published version of the library.

I believe this is the same rationale that React is using for links in dev warnings. All of these links redirect to the actual page.

**Comment by MatanBobi** [comment]
> We're actually less backwards compatible. Note that we can't change these links once published. If we decide to move the page then any version published will have 404 links. We could then decide to make redirect but we might as well use a permalink to begin with. Otherwise we have to maintain redirects for every published version of the library.
> 
> I believe this is the same rationale that React is using for links in dev warnings. All of these links redirect to the actual page.

That's a good point, I didn't think about it that way..
So I'll close this one :)
Thanks!

**Pull request closed without merging**
