### PR TITLE
feat: Support anonymous custom elements when pretty printing DOM

### PR DESCRIPTION
**Pull request by KonnorRogers**
Fixes https://github.com/testing-library/dom-testing-library/issues/1191

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
Thank you. Please add a test illustrating the intended behavior

**Comment by KonnorRogers** [comment]
@eps1lon I could see how that could be helpful 😆 let me work on it.

**Comment by KonnorRogers** [comment]
@eps1lon Done!

I also noticed there was no test for named custom elements so I added one.

Let me know if there's anything else I can do :)

**Review by eps1lon — APPROVED** [review]
Thank you!

**Pull request merged**
