### PR TITLE
fix: shouldExcludeFromA11yTree runs in IE11

### PR DESCRIPTION
**Pull request by briandipalma**
IE11 returns `undefined` for missing `parentElement`.

fix: In IE11 when an element lacks `parentElement` it returns `undefined` instead of `null`.

**Why**: Because otherwise you get these errors

```
TypeError: Unable to get property 'hidden' of undefined or null reference
	error properties: Object({ number: -2146823281 })
	    at <Jasmine>
	   at shouldExcludeFromA11yTree (eval code:824:5)
	   at Anonymous function (eval code:995:5)
	   at Anonymous function (eval code:28:7)
	   at filter (eval code:11:5)
	   at queryAllByRole (eval code:994:3)
```

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/alexkrolick/testing-library-docs) N/A
- [ ] I've prepared a PR for types targetting https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom N/A
- [ ] Tests N/A
- [x ] Ready to be merged

### CODE REVIEW

**Comment by eps1lon** [comment]
Could you include a reproduction that fails with IE 11? This would help a lot :pray:

**Comment by briandipalma** [comment]
Yes it seems like it's not implemented on `Node` `Only supported on Element.` from https://developer.mozilla.org/en-US/docs/Web/API/Node/parentElement

But the element that failed for us was an SVG and I found this: https://stackoverflow.com/a/36270354/1927079

```In Internet Explorer, parentElement is undefined for SVG elements, whereas parentNode is defined.```

Do your tests run in IE11?

**Comment by eps1lon** [comment]
> But the element that failed for us was an SVG and I found this:

Interesting. I'll verify that and add it to the MDN docs since `SVGElement` inherits from `Element`.

> Do your tests run in IE11?

We don't run any tests in browsers and so far browser support hasn't been a priority from what I can tell. I use this library in browser tests though so anytime I do find one I'll try to fix it (#362, #363).

**Comment by briandipalma** [comment]
I'll try and add a test that covers the failure I see here.

**Comment by briandipalma** [comment]
Added a test but this would only ever fail in IE11.

**Comment by briandipalma** [comment]
Updated the tests, is this what you were thinking?

**Comment by briandipalma** [comment]
Is this OK?

**Pull request merged**
