### PR TITLE
chore: Update MAINTAINING.md

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
👍

**Comment by nickmccurdy** [comment]
How is doctoc being used here? If it's part of kcd-scripts I feel like the upstream MAINTAINING.md should be updated. If not, I'm curious if this should be added to either kcd-scripts or other testing-library repositories manually.

**Comment by kentcdodds** [comment]
Yes, this should be applied to any repo that's using actions.

**Comment by nickmccurdy** [comment]
I'm working on updating `generator-kcd-oss` from `dom-testing-library`, which will include this and other fixes

**Pull request merged**
