### PR TITLE
fix: Use import instead of require

### LINKED ISSUE #793: Module require error in version 7.26.1
Node 12.18.4 and @testing-library/dom 7.26.1, pinning to a lower version of @testing-library/dom solved the issue for me. I believe this was the call [site](https://github.com/testing-library/dom-testing-library/blob/bc65b91fed81d900e8eb2aff1813752a4f487869/src/get-node-text.js#L1).

Require was triggered by Cypress not sure if this has anything to do with it though.

```
Oops...we found an error preparing this test file:

  support/index.js

The error was:

Error: Webpack Compilation Error
/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js
Module not found: Error: Can't resolve './helpers' in '/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library'
Looked for and couldn't find the file at the following paths:
[/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/helpers]
[/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/helpers.js]
[/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/helpers.json]
[/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/helpers.jsx]
[/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/helpers.mjs]
[/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/helpers.coffee]
[/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/helpers.ts]
[/Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/helpers.tsx]
 @ /Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js 387:15-35
 @ /Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/cypress/dist/index.js
 @ /Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/cypress/dist/add-commands.js
 @ /Users/albert.still/Documents/GitHub/fe-server-search-listings/node_modules/@testing-library/cypress/add-commands.js
 @ ./support/index.js

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

### PR DESCRIPTION
**Pull request by eps1lon**
Description for 53b547f016b673a3299c9782286f8e3da53a95b3 which I accidentally committed to `master`

**What**:

Closes #793

**Why**:

Seems considered `require`ed files as external

**How**:

Use `import` instead of `require`

**Checklist**:

- ~[ ]~ Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- ~[ ]~ Tests
- ~[ ]~ Typescript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Comment by eps1lon** [comment]
Hopefully this triggers a release.

**Comment by marcosvega91** [comment]
🤦 my fault

**Comment by eps1lon** [comment]
>  my fault

There are no mistakes. Only missing tests :wink:

**Comment by marcosvega91** [comment]
How this error could be intercepted by a test case? Test already using `TEXT_NODE` but no test was broken.

**Comment by eps1lon** [comment]
> How this error could be intercepted by a test case? Test already using TEXT_NODE but no test was broken.

We could add some fixtures for various build setups but that's probably just overkill. I just wanted to say that you shouldn't stress about it :smiley:

**Comment by marcosvega91** [comment]
> We could add some fixtures for various build setups but that's probably just overkill

ah ok that makes sense now. 

> I just wanted to say that you shouldn't stress about it 😃

hahah no stress, it was for the stupid error hahahahah

**Pull request merged**
