### PR TITLE
Release Next breaking changes

### PR DESCRIPTION
**Pull request by kentcdodds**
**What**: Check commits

**Why**: Because breaking changes are sometimes necessary

**How**: To update the changelog correctly and release these at the same time, we'll merge this using rebase (not squash and merge).

**Checklist**:

- [x] Documentation added to the [docs site](https://github.com/alexkrolick/testing-library-docs). https://github.com/alexkrolick/testing-library-docs/pull/84
- [x] Typescript definitions updated... I think so? I'm not sure. Someone will have to update it later.
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by kentcdodds** [comment]
What do you all say we make the testing-library GitHub org at the same time?

**Comment by bcarroll22** [comment]
I'm game 👍

**Comment by bcarroll22** [comment]
@kentcdodds just realized, is it possible within the new org to make each maintainer admin of their repo?

**Comment by kentcdodds** [comment]
I believe so.

**Comment by kentcdodds** [comment]
Well... Let's go ahead and get this released :)

**Comment by alexkrolick** [comment]
LGTM, fwiw :)

**Pull request merged**
