### PR TITLE
chore(event): cleanup commented out code

### PR DESCRIPTION
**Pull request by JonathanStoye**
**What**/**Why**/**How**:

https://github.com/testing-library/dom-testing-library/issues/423

**Checklist**:

- [ ] Documentation added to the [docs site](https://github.com/testing-library/testing-library-docs) N/A
- [ ] I've prepared a PR for types targeting [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom) N/A
- [ ] Tests N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by eps1lon** [comment]
I thought all the "all-contributors" related stuff is handled by a bot. Any reason this has to be included in this PR?

**Comment by JonathanStoye** [comment]
@eps1lon I am sorry, it used to be that I have to do it myself last time I contributed here. Let me remove that real quick.

**Comment by kentcdodds** [comment]
@all-contributors please add @JonathanStoye for code

**Pull request merged**
