### PR TITLE
Feature: adds aria-expanded filter to *ByRole

### PR DESCRIPTION
**Pull request by goblindegook**
**What**: Adds an `expanded` filter to `*ByRole` queries.

**Why**: Allow supporting roles to be filtered by the `aria-expanded` widget attribute.

**How**: Implemented in a similar pattern as other attribute filters.

**Checklist**:

- [x] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [x] Tests
- [x] Typescript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Review by nickmccurdy — APPROVED** [review]
The code looks good, though I wonder if this has an impact on `*ByRole`'s performance

**Comment by goblindegook** [comment]
I imagine the impact on performance comes before --- the change affects filtering logic that comes after that.

I am wondering though, given that in this instance we're filtering by an attribute, wouldn't it be possible to replace that `container.querySelectorAll('*')` at the start with a `container.querySelectorAll('[aria-foo="bar"]')`?

**Review by eps1lon — APPROVED** [review]

**Comment by eps1lon** [comment]
> I am wondering though, given that in this instance we're filtering by an attribute, wouldn't it be possible to replace that container.querySelectorAll('*') at the start with a container.querySelectorAll('[aria-foo="bar"]')

Create a benchmark, measure and share the results. I believe I checked this in the past and only observed negligible gains.

**Comment by eps1lon** [comment]
"while dany kind of forgot"-meme format captioned with "While Sebastian kind of forgout about this PR"

**Pull request merged**
