### PR TITLE
chore(validate): Filter out all-contributors branches

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by nickmccurdy** [comment]
This might be using a broken version of `eslint-plugin-jest`. Could you please push an empty commit to rerun the build using the latest?

**Comment by kentcdodds** [comment]
I just triggered a re-run

**Comment by nickmccurdy** [comment]
Out of curiosity how did you do that? I thought it wasn't possible in GitHub Actions without the `workflow_dispatch` event in the config.

**Comment by kentcdodds** [comment]
I just clicked the rerun jobs button

**Comment by nickmccurdy** [comment]
Oh... I didn't notice that 😆  nevermind

**Pull request merged**
