### PR TITLE
Fix typo in type definition for suggestions

### PR DESCRIPTION
**Pull request by geoffharcourt**
**What**:
Fixing a type definition typo

**Why**:

It appears that in 7f8a15e there was a subtle typo where the lower-case
`testid` was misspelled.

**How**:
I fixed the typo.

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs) N/A
- [ ] Tests N/A
- [X] Typescript definitions updated N/A
- [X] Ready to be merged

### CODE REVIEW

**Comment by marcosvega91** [comment]
😣 my fault

**Comment by kentcdodds** [comment]
No worries! Thank you 😁

**Comment by kentcdodds** [comment]
@all-contributors please add @geoffharcourt for code

**Pull request merged**
